config/routes.rb
JlCompliance::Application.routes.draw do
  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "jobs#index"

  resources :jobs do
    resources :subcontractor_at_jobs, only: :index
    resources :supplier_trucks, only: :index
    resources :subcontractor_trucks, only: :index
  end

  resources :subcontractor_at_jobs, only: :show
  resources :subcontractor_trucks, only: :show
  resources :photos, only: [:show, :create]

end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :name

  has_many :subcontractor_at_jobs, inverse_of: :job
  accepts_nested_attributes_for :subcontractor_at_jobs,  allow_destroy: true
  attr_accessible :subcontractor_at_jobs_attributes,     allow_destroy: true

  has_many  :subcontractors, :through => :subcontractor_at_jobs

  has_many :subcontractor_trucks, inverse_of: :job
  accepts_nested_attributes_for :subcontractor_trucks,  allow_destroy: true
  attr_accessible :subcontractor_trucks_attributes,     allow_destroy: true

  has_many :supplier_trucks, inverse_of: :job
  accepts_nested_attributes_for :supplier_trucks, allow_destroy: true
  attr_accessible :supplier_trucks_attributes,    allow_destroy: true

  validates :name, presence: true

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = Job.all
    @title = "Jobs"
  end

  def show
    @job = Job.find(params[:id])
    @title = @job.name
    @back_target = jobs_path
  end

end

app/views/jobs/index.html.erb
<ul data-role="listview" data-inset="true" data-filter="true">
  <% @jobs.each do |job| %> 
  <li>
    <%= link_to job.name, job %>
  </li>
  <% end %> 
</ul>

app/views/jobs/show.html.erb
<ul data-role="listview" data-inset="true" data-filter="true">
  
  <li>
    <%= link_to "Subcontractors", job_subcontractor_at_jobs_path(@job) %>
    <span class="ui-li-count"><%= @job.subcontractor_at_jobs.count %></span>
  </li>
  

  <li>
    <%= link_to "Suppliers", job_supplier_trucks_path(@job) %>
    <span class="ui-li-count"><%= @job.supplier_trucks.count %></span>
  </li>
  

  <li>
    <%= link_to "Truckers", job_subcontractor_trucks_path(@job) %>
    <span class="ui-li-count"><%= @job.subcontractor_trucks.count %></span>
  </li>
  

</ul>