config/routes.rb
JlCompliance::Application.routes.draw do
  devise_for :users

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root :to => "jobs#index"

  resources :jobs do
    resources :subcontractor_at_jobs, only: :index
    resources :supplier_trucks, only: :index
    resources :subcontractor_trucks, only: :index
  end

  resources :subcontractor_at_jobs, only: :show
  resources :subcontractor_trucks, only: :show
  resources :photos, only: [:show, :create]

end

app/models/supplier_truck.rb
class SupplierTruck < ActiveRecord::Base
  attr_accessible :supplier_name, :plate

  has_many :tickets, inverse_of: :supplier_truck
  accepts_nested_attributes_for :tickets, allow_destroy: true
  attr_accessible :tickets_attributes,    allow_destroy: true

  belongs_to  :job, inverse_of: :supplier_trucks
  attr_accessible :job_id
  validates :job, presence: true

  validates               :supplier_name, presence: true
  validates               :plate, presence: true
  alias_attribute :name,  :plate
end

app/controllers/supplier_trucks_controller.rb
class SupplierTrucksController < ApplicationController 
  def index
    @supplier_trucks = SupplierTruck.where(job_id: params[:job_id])
    @back_target = job_path(params[:job_id])
  end

  def show
    @supplier_truck = SupplierTruck.find(params[:id])
    @title = @supplier_truck.name
    @back_target = job_supplier_trucks_path(@supplier_truck.job)
  end
end

app/views/supplier_trucks/index.html.erb
<a href="#" data-photo-target="<%= photos_url %>" data-role="button" data-theme="b" data-inline="true">
  <%= icon('camera-retro', 'icon-3x', 'custom-button-icon') %> Take Photo
</a>
<p>
  Use this to take a photo of a truck or delivery ticket, and send it to the back office
</p>

app/views/supplier_trucks/show.html.erb
<ul data-role="listview" data-inset="true" data-filter="true">
  <% @supplier_truck.tickets.each do |ticket| %> 
    <li>
      <%= link_to ticket_path(ticket) do %>
        <div class="ui-grid-a">
          <div class="ui-block-a">thumb</div>
          <div class="ui-block-b" class="item_info">
            <div><%= "Ticket ##{ticket.number}" %></div>
            <div>
                <%= ticket.approved_date ? 
                "Approved #{ticket.approved_date}" : "Not yet approved" %>
            </div>
          </div>
        </div>
      <% end %>         
    </li>
  <% end %> 
</ul>